In [6]:
import pandas as pd
df = pd.read_csv("dataset/synthetic_logs.csv")
df.head()

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert

In [7]:
df.source.unique()

<StringArray>
[      'ModernCRM', 'AnalyticsEngine',        'ModernHR',   'BillingSystem',
   'ThirdPartyAPI',       'LegacyCRM']
Length: 6, dtype: str

In [8]:
df.target_label.unique()

<StringArray>
[        'HTTP Status',      'Critical Error',      'Security Alert',
               'Error', 'System Notification',      'Resource Usage',
         'User Action',      'Workflow Error', 'Deprecation Warning']
Length: 9, dtype: str

In [11]:
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN
import numpy as np

#Load pre-trained SentenceTransformer Model
model = SentenceTransformer('all-MiniLM-L6-v2')

#generate embeddings for log messages
embeddings = model.encode(df['log_message'].tolist())
embeddings[:2]

array([[-1.02939658e-01,  3.35459076e-02, -2.20260452e-02,
         1.55100238e-03, -9.86919273e-03, -1.78956255e-01,
        -6.34410605e-02, -6.01761863e-02,  2.81108301e-02,
         5.99620342e-02, -1.72619056e-02,  1.43371313e-03,
        -1.49560124e-01,  3.15283332e-03, -5.66031076e-02,
         2.71685813e-02, -1.49890380e-02, -3.54037471e-02,
        -3.62936407e-02, -1.45410290e-02, -5.61491679e-03,
         8.75538141e-02,  4.55120839e-02,  2.50964109e-02,
         1.00187147e-02,  1.24267694e-02, -1.39923632e-01,
         7.68696144e-02,  3.14095356e-02, -4.15251637e-03,
         4.36902493e-02,  1.71250291e-02, -8.00951049e-02,
         5.74006177e-02,  1.89091284e-02,  8.55261385e-02,
         3.96398529e-02, -1.34371802e-01, -1.44369516e-03,
         3.06704547e-03,  1.76854089e-01,  4.44884971e-03,
        -1.69275030e-02,  2.24266127e-02, -4.35050204e-02,
         6.09026849e-03, -9.98166855e-03, -6.23973049e-02,
         1.07372068e-02, -6.04897272e-03, -7.14660585e-02,
        -8.45808443e-03, -3.18019725e-02, -1.00518405e-01,
         2.25882191e-04, -1.89340841e-02, -3.17794010e-02,
         4.00860570e-02,  2.19177771e-02, -2.59528197e-02,
         5.84525131e-02, -8.12509507e-02,  2.12028306e-02,
        -5.02687208e-02,  1.32058123e-02,  1.32680393e-03,
         2.27063559e-02, -3.45793366e-02,  3.91547531e-02,
        -2.09433381e-02,  3.24819540e-03,  4.43960764e-02,
        -9.85357538e-02, -2.88894456e-02, -6.85024587e-03,
         5.38819581e-02,  6.46110624e-02, -2.45059859e-02,
         9.21828821e-02, -7.49869570e-02,  1.23995375e-02,
        -1.00026578e-01, -4.64910492e-02,  6.01570494e-02,
        -2.46480703e-02, -7.08075687e-02, -2.77270097e-02,
         9.72611755e-02,  3.85841131e-02, -1.44293131e-02,
        -7.46873149e-04, -1.04304869e-02, -1.61842760e-02,
         4.43627946e-02,  9.26001836e-03,  7.14165494e-02,
         6.37917444e-02,  4.94930781e-02, -6.02567382e-02,
         4.04805802e-02, -3.42860259e-02, -1.93881001e-02,
         6.61233515e-02,  6.01589195e-02,  1.09370947e-02,
        -5.38626965e-03,  1.44579951e-02,  9.25429687e-02,
        -3.14563662e-02, -1.84350908e-02,  9.91878752e-03,
        -1.85574926e-02,  1.31285691e-03,  2.26819247e-05,
         2.02737516e-03,  2.75256187e-02, -4.81927618e-02,
         5.42825758e-02, -7.32066631e-02,  4.88667563e-02,
         4.98490334e-02, -9.01136268e-03, -4.68905680e-02,
        -4.25887145e-02, -8.19524005e-02,  3.87106352e-02,
         7.85503834e-02,  1.46077052e-32,  1.66706461e-02,
         5.25494367e-02, -1.82450190e-02, -1.26686115e-02,
         6.52837083e-02, -2.11777296e-02, -4.06322926e-02,
         4.14948352e-02, -2.48361547e-02, -1.33067947e-02,
        -5.46752848e-02, -5.99164574e-04, -4.89248801e-03,
        -6.27359748e-02, -3.84878367e-02, -6.13543987e-02,
         8.27405676e-02,  2.34380364e-02, -8.63085501e-03,
         1.31002264e-02,  6.44214824e-02, -4.41361740e-02,
        -6.98633939e-02, -7.36060217e-02, -4.33264114e-02,
         6.96518831e-03, -5.05956523e-02, -1.60911884e-02,
        -5.66793941e-02,  3.35454452e-03,  5.34115434e-02,
         2.47761682e-02, -1.47986384e-02, -2.93242503e-02,
         7.30228424e-02, -1.86833590e-02,  8.13137293e-02,
        -2.69967578e-02, -5.68055622e-02, -6.59388080e-02,
        -5.95397595e-03,  2.85312496e-02, -7.85358176e-02,
        -2.76693422e-03, -3.26474337e-03, -9.28333476e-02,
        -7.27363452e-02, -3.31903584e-02,  1.01411156e-01,
         9.79881808e-02, -9.78740752e-02,  1.98667776e-02,
         2.38836743e-02, -1.81673057e-02, -3.73708159e-02,
         1.96559215e-03,  6.34425730e-02,  1.18270582e-02,
        -1.12041468e-02, -3.87316346e-02,  9.32424366e-02,
         4.26628487e-03, -1.66872721e-02, -6.87464550e-02,
         1.55119151e-02, -4.97754924e-02,  3.34492624e-02,
         8.00032243e-02,  2.12282725e-02,  1.34581864e-01,
        -2.30730064e-02,  5.53858876e-02,  3.07557881e-02,
        -2.93905903e-02,  2.31905505e-02, -9.34306830e-02,
         7.58035481e-02, -5.21203037e-03, -5.14523312e-02,
         3.32689248e-02,  3.67963761e-02, -1.06450971e-02,
         1.01635335e-02, -2.07650457e-02, -5.85519001e-02,
         4.79328968e-02,  2.13694312e-02,  8.76213163e-02,
         3.35489819e-03, -3.80336456e-02, -1.81205124e-02,
         6.87440066e-03,  5.15879542e-02, -4.75599021e-02,
        -6.12065308e-02, -1.45483589e-32,  4.12804866e-03,
         4.59643407e-03, -5.63901775e-02,  4.32479661e-03,
        -1.09442614e-03,  9.31955036e-03, -2.20269021e-02,
         5.79565428e-02, -1.44787543e-02,  4.64156866e-02,
         1.43542841e-01, -6.89756349e-02,  6.09631166e-02,
        -8.93744454e-02,  2.40918528e-02,  2.06009988e-02,
        -2.82415617e-02, -6.48316070e-02,  5.64795323e-02,
        -7.48333847e-03, -3.52058224e-02,  8.51059780e-02,
         1.30359586e-02,  2.02257670e-02, -1.44390445e-02,
        -4.63718474e-02,  1.77209862e-02,  1.59105603e-02,
        -9.51009095e-02, -3.54527757e-02,  2.08696127e-02,
         3.84379528e-03, -8.77918079e-02,  6.44574314e-02,
         1.44170737e-02,  3.84734804e-03,  4.70991395e-02,
         4.94661927e-02,  1.53861940e-02, -2.59578507e-02,
         9.10895243e-02,  1.83307827e-02, -5.89206964e-02,
         2.51991898e-02, -3.30374166e-02,  8.23344737e-02,
         1.74791664e-02,  6.48047328e-02, -1.19673982e-02,
        -3.31778005e-02,  3.00177373e-02,  3.54220495e-02,
        -1.39623741e-02,  6.69272766e-02,  3.87919582e-02,
         6.06916398e-02,  1.17964006e-03, -2.38786787e-02,
        -1.26930431e-01,  1.13847675e-02,  1.59290340e-02,
        -1.29425973e-02, -8.63247812e-02,  8.53659306e-03,
         6.03761226e-02,  1.51121691e-02, -1.19132377e-01,
         1.15234843e-02,  5.97088858e-02, -3.93345393e-02,
         1.55674582e-02,  1.04602240e-02, -4.72457781e-02,
        -2.59243529e-02,  9.98532586e-03,  3.07146609e-02,
        -7.14844018e-02,  6.98966533e-03, -1.55133605e-02,
         2.18864325e-02, -2.78145913e-02,  6.92734122e-02,
        -2.75903996e-02,  2.62429491e-02,  3.52562517e-02,
        -4.26418148e-02,  7.46316509e-04,  6.59866482e-02,
        -5.15105091e-02, -3.58433761e-02, -6.53441809e-03,
        -2.75858752e-02, -1.00125596e-01,  7.83325508e-02,
        -1.45799490e-02, -6.18457250e-08,  2.00325418e-02,
         6.59786463e-02, -2.04702709e-02,  1.64044499e-02,
         7.63001069e-02,  7.32182190e-02,  5.65791316e-03,
        -6.97715557e-04, -3.63795040e-03,  6.02394417e-02,
        -3.27187441e-02, -6.45838007e-02, -5.97952567e-02,
        -1.76695604e-02,  6.10144483e-03, -5.63489227e-03,
        -1.22972235e-01,  6.35818169e-02, -2.19432414e-02,
        -1.16406567e-01,  2.34365407e-02, -7.23525062e-02,
         2.31774021e-02, -6.55987710e-02, -7.42682591e-02,
         2.60146149e-02,  3.59757729e-02,  7.68432990e-02,
        -3.08056623e-02, -2.34793741e-02, -6.30426556e-02,
        -3.62157561e-02, -1.03560146e-02, -4.75603044e-02,
        -2.87522357e-02,  2.96400748e-02, -5.26897470e-03,
         5.67889437e-02, -3.74491094e-03,  3.09612658e-02,
         3.48227881e-02,  3.78607400e-02,  2.10155882e-02,
         2.70691700e-02,  5.25520556e-02,  7.16229305e-02,
        -5.53756580e-03,  4.01093513e-02,  5.16276397e-02,
        -2.67314464e-02,  5.94224669e-02, -4.29223664e-02,
        -1.19761312e-02,  3.05986162e-02, -7.40331635e-02,
         1.84221659e-02, -8.64861999e-03, -8.83558542e-02,
        -5.91983981e-02, -1.00883008e-04,  1.12913609e-01,
         4.57783276e-03, -4.25972342e-02,  3.22622037e-03],
       [ 8.04568827e-03, -3.57392244e-02,  4.93873246e-02,
        -7.19187781e-03,  6.17643353e-04, -9.05685052e-02,
         5.75594865e-02, -4.39445786e-02,  1.74750928e-02,
         5.21202609e-02, -4.62332182e-02,  2.49039344e-02,
         4.80811037e-02,  6.86636269e-02,  3.56147699e-02,
         3.00088935e-02,  2.61450764e-02, -9.05241966e-02,
        -8.02173167e-02,  5.04851155e-02, -7.90870488e-02,
        -1.76851591e-03, -2.48927288e-02,  9.02152807e-02,
         5.83688775e-03, -6.91071376e-02, -6.67965785e-02,
        -6.99117687e-03, -1.04566067e-01, -2.66474262e-02,
         3.05640437e-02,  2.02934202e-02,  2.25454140e-02,
        -4.22681170e-03,  1.11172833e-02,  6.78261220e-02,
         1.06073292e-02,  7.56636113e-02, -8.22778270e-02,
         8.45728349e-03, -6.97611719e-02, -4.21974398e-02,
        -1.05675822e-02,  2.23672967e-02,  5.64496703e-02,
         8.16499535e-03,  1.09344058e-01,  3.16565260e-02,
        -1.76924430e-02, -3.21071297e-02, -3.39975767e-02,
        -4.91855317e-04,  3.72880138e-03,  2.83772312e-02,
        -1.28521305e-02, -1.07931881e-03, -6.32418692e-02,
         6.89900741e-02,  1.77269913e-02, -5.20959347e-02,
         8.28306563e-03,  5.45032024e-02, -5.42099290e-02,
        -4.53332923e-02, -4.07494120e-02, -2.82698553e-02,
         1.23605793e-02, -2.13815905e-02, -2.36265697e-02,
         1.25318225e-02, -2.37170830e-02,  3.97411212e-02,
        -1.24362186e-01,  7.60625973e-02,  5.50833195e-02,
         8.28217119e-02,  2.97119375e-02, -1.84067804e-02,
        -1.96194388e-02,  5.54319583e-02, -3.49143744e-02,
        -4.14677337e-02, -3.37047540e-02,  7.31324628e-02,
         4.41837162e-02,  2.55246032e-02, -8.26404616e-03,
        -1.07323481e-02, -4.26243804e-02, -2.84964102e-03,
         7.38558993e-02,  2.27768105e-02,  7.15358357e-04,
         4.36012261e-02,  5.09079918e-02,  6.38482422e-02,
        -2.73155589e-02, -6.55021369e-02, -7.69265592e-02,
         3.55171412e-02,  9.60494429e-02,  2.18195431e-02,
         1.20155085e-02, -1.17863966e-02, -4.57934849e-03,
        -8.58035870e-03,  3.37149911e-02,  2.31918171e-02,
        -7.58325458e-02, -5.23878783e-02,  4.53933924e-02,
        -3.80786099e-02, -3.34904455e-02,  9.20352340e-02,
         2.87689045e-02, -3.33817229e-02, -1.95855135e-03,
        -3.04527202e-04, -1.70498863e-02,  2.85336170e-02,
        -8.81095976e-02, -4.02252637e-02, -4.00093310e-02,
        -1.03193512e-02, -2.51968522e-02,  2.14093141e-02,
         1.31045327e-01, -5.29633628e-34, -1.09651722e-01,
         1.29811689e-02,  5.92656992e-03,  4.73506525e-02,
        -8.60294141e-03, -3.67089808e-02,  3.05214804e-02,
         5.53066991e-02, -4.71985340e-02, -1.25119016e-02,
        -1.15366451e-01,  9.08002816e-03,  1.07346535e-01,
        -4.94734645e-02, -1.34290690e-02, -4.61562313e-02,
         2.45319884e-02,  9.45083797e-03,  2.04324313e-02,
        -3.99918072e-02, -4.67826203e-02,  2.21171528e-02,
        -4.58187647e-02, -8.13268125e-03, -7.65662920e-03,
         1.92283969e-02,  4.85844240e-02, -2.55902410e-02,
         1.61546015e-03, -1.37180351e-02,  9.67306364e-03,
         7.36415107e-03,  1.14087826e-02,  1.28853470e-01,
         7.71843176e-03,  7.06362575e-02,  2.54451837e-02,
         4.06524539e-02,  2.44039111e-02,  1.43776434e-02,
        -6.00932240e-02,  7.38180727e-02, -2.44701821e-02,
         8.98901448e-02,  3.17051308e-03,  1.01834439e-01,
         4.17741537e-02, -5.95178008e-02, -3.23181301e-02,
         3.80938500e-02,  1.21155735e-02, -4.07835022e-02,
         2.84823570e-02,  4.90988642e-02, -9.35696252e-03,
         6.50074035e-02,  7.23532289e-02, -1.67792812e-02,
        -8.22414737e-03, -1.61573160e-02,  5.96225671e-02,
        -3.36084068e-02,  2.12108139e-02, -6.06090873e-02,
         1.54377669e-01, -7.24146590e-02, -3.77272107e-02,
        -3.26889381e-02, -1.80384505e-03, -1.01960525e-02,
        -1.60677044e-03, -6.91846684e-02,  8.28444511e-02,
         9.88840386e-02,  3.45472968e-03, -9.90247428e-02,
        -3.52826715e-02, -7.13179111e-02, -4.96000610e-02,
        -3.43954563e-02, -8.13042298e-02,  4.81447428e-02,
         5.00677759e-03, -2.21499596e-02, -5.60056902e-02,
         1.00067658e-02, -3.59793641e-02,  1.06184334e-01,
        -4.54196557e-02,  7.16393217e-02, -2.36773379e-02,
         9.98141803e-03,  2.73602251e-02,  1.05985507e-01,
         4.60164025e-02,  9.59027984e-34, -1.12306982e-01,
         2.78912596e-02, -3.35901678e-02,  5.39242215e-02,
        -2.22291742e-02,  1.53769460e-02,  3.10411751e-02,
         3.39010693e-02,  7.43166804e-02,  3.42471190e-02,
        -3.35056381e-03, -2.05350518e-02, -3.62369567e-02,
         2.29334384e-02, -3.01992167e-02, -1.00819930e-01,
         3.29193696e-02,  6.77542612e-02,  1.35644823e-02,
        -5.20552043e-03, -6.58159405e-02,  9.54550654e-02,
        -1.34038674e-02,  1.53884878e-02, -7.22936019e-02,
         9.67835784e-02, -8.08119327e-02, -4.53450857e-03,
        -6.42011166e-02, -4.99278717e-02,  4.64197844e-02,
         2.21340563e-02,  3.13109718e-02,  9.13569406e-02,
        -4.61120307e-02, -1.02761082e-01,  3.04415710e-02,
         5.09876050e-02,  6.70141131e-02,  1.04042552e-02,
         1.63533855e-02,  3.92031148e-02,  2.17154156e-02,
         5.36603890e-02,  3.62809412e-02, -4.22139913e-02,
        -2.47227270e-02,  1.90311782e-02,  3.61723900e-02,
         6.37021512e-02, -3.21581750e-03, -8.50391481e-03,
         3.94655690e-02,  9.02657956e-03,  1.93095449e-02,
         6.60717785e-02,  1.02695301e-02, -4.43853959e-02,
        -1.56523343e-02, -1.55714285e-02,  1.32904137e-02,
        -1.16108870e-02,  4.21831906e-02, -5.44776991e-02,
         1.29237205e-01, -2.25757267e-02,  5.26204035e-02,
        -1.58436671e-02,  9.33164880e-02,  6.38019899e-03,
        -9.36165359e-03, -6.08875267e-02, -3.27307954e-02,
        -3.44816409e-02,  3.29973884e-02, -4.79391776e-02,
        -9.81301218e-02,  2.91165318e-02, -2.70903558e-02,
         1.81866679e-02, -1.73860192e-02, -4.40371595e-02,
        -7.97002614e-02,  3.01646702e-02, -6.35260865e-02,
         1.25963148e-02,  8.50250050e-02, -4.58910801e-02,
         5.81017770e-02, -2.71002855e-02,  8.42775777e-02,
        -4.09972444e-02, -3.37656438e-02,  1.02088647e-02,
        -2.54193135e-02, -1.40610315e-08,  4.94446717e-02,
        -9.04356241e-02, -6.06709793e-02,  8.29529762e-02,
        -3.29032466e-02,  4.14911099e-02,  9.99588892e-03,
         6.96139270e-03,  3.99235217e-03, -3.24333757e-02,
        -3.14657167e-02, -5.33161238e-02, -3.80912647e-02,
         1.62076633e-02,  2.45779362e-02, -7.26419240e-02,
        -6.56893328e-02, -8.23131576e-02, -8.00500810e-02,
        -5.36649339e-02,  5.60895056e-02, -1.10913254e-02,
         9.62131075e-04, -1.22690305e-01, -5.13836704e-02,
         9.96705797e-03,  1.00696497e-02,  1.07073039e-01,
         1.19758090e-02,  1.00423107e-02, -6.28261566e-02,
        -7.49697089e-02, -6.34071417e-03, -2.72200853e-02,
        -1.28096148e-01, -2.62459684e-02, -1.81465074e-02,
        -9.85359997e-02, -3.02989986e-02, -4.02615033e-02,
         9.94290709e-02,  5.35999835e-02,  2.74899211e-02,
        -5.53685380e-03,  8.43570456e-02,  8.35161582e-02,
         3.74304168e-02,  7.11937770e-02,  2.98902858e-02,
         2.32728850e-02, -3.62112671e-02,  6.20540045e-02,
         2.15148237e-02,  5.19733354e-02,  1.45338085e-02,
        -4.60966341e-02,  5.02553806e-02, -7.27027655e-02,
         2.92778909e-02,  5.62662780e-02, -3.86354923e-02,
         1.53832156e-02, -6.23094700e-02, -2.77467091e-02]], dtype=float32)

In [14]:
#Perform DBCAN clustering
dbscan = DBSCAN(eps=0.2, min_samples = 5, metric='cosine')
clusters = dbscan.fit_predict(embeddings)

#Add cluster labels to the dataframe
df['cluster'] = clusters
df.head()

,timestamp,source,log_message,target_label,complexity,cluster
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,-1
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0

In [15]:
df[df.cluster == 1].head()

,timestamp,source,log_message,target_label,complexity,cluster
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
10,8/9/2025 18:58,ModernCRM,Email server encountered a sending fault,Error,bert,1
217,1/22/2025 5:45,BillingSystem,Mail service encountered a delivery glitch,Error,bert,1
248,5/2/2025 23:04,ModernHR,Service disruption caused by email sending error,Critical Error,bert,1
265,3/30/2025 23:53,ModernCRM,Email system had a problem sending emails,Error,bert,1

In [17]:
df['cluster'] = 5

In [19]:
cluster_counts = df['cluster'].value_counts()
large_clusters = cluster_counts[cluster_counts > 10].index

for clusters in large_clusters:
    print(f"Cluster {clusters}: ")
    print(df[df['cluster'] == clusters]['log_message'].head(5).to_string(index=False))
    print()

Cluster 5:
nova.osapi_compute.wsgi.server [req-b9718cd8-f6...
    Email service experiencing issues with sending
         Unauthorized access to data was attempted
nova.osapi_compute.wsgi.server [req-4895c258-b2...
nova.osapi_compute.wsgi.server [req-ee8bc8ba-92...

In [27]:
import re
def classify_with_regex(log_message):
    regex_patterns = {
        r"User User\d+ logged (in|out).": "User Action",
        r"Backup (started|ended) at .*": "System Notification",
        r"Backup completed successfully.": "System Notification",
        r"System updated to version .*": "System Notification",
        r"File .* uploaded successfully by user .*": "System Notification",
        r"Disk cleanup completed successfully.": "System Notification",
        r"System reboot initiated by user .*": "System Notification",
        r"Account with ID .* created by .*": "User Action"
    }
    for pattern, label in regex_patterns.items():
        if re.search(pattern, log_message, re.IGNORECASE):
            return label
        return None

In [32]:
classify_with_regex("User User494 logged in.")

'User Action'

In [36]:
df['regex_label'] = df['log_message'].apply(classify_with_regex)
df[df.regex_label.isna()]

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,5,NaN
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,5,NaN
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,5,NaN
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,5,NaN
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,5,NaN
...,...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert,5,NaN
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert,5,NaN
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert,5,NaN
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,5,NaN
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert,5,NaN

In [38]:
df_non_regex = df[df['regex_label'].isnull()].copy()
df_non_regex

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,5,NaN
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,5,NaN
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,5,NaN
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,5,NaN
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,5,NaN
...,...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert,5,NaN
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert,5,NaN
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert,5,NaN
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,5,NaN
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert,5,NaN

In [ ]:
print(df_non_regex['target_label'].value_counts()[df_non_regex['target_label'].value_counts() <= 5].index.tolist())

In [40]:
df_non_legacy = df_non_regex[df_non_regex.source!='LegacyCRM']
df_non_legacy.source.unique()

<StringArray>
['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem', 'ThirdPartyAPI']
Length: 5, dtype: str

In [41]:
filtered_embeddings = model.encode(df_non_legacy['log_message'].tolist())
filtered_embeddings[:2]

array([[-1.02939658e-01,  3.35459076e-02, -2.20260452e-02,
         1.55100238e-03, -9.86919273e-03, -1.78956255e-01,
        -6.34410605e-02, -6.01761863e-02,  2.81108301e-02,
         5.99620342e-02, -1.72619056e-02,  1.43371313e-03,
        -1.49560124e-01,  3.15283332e-03, -5.66031076e-02,
         2.71685813e-02, -1.49890380e-02, -3.54037471e-02,
        -3.62936407e-02, -1.45410290e-02, -5.61491679e-03,
         8.75538141e-02,  4.55120839e-02,  2.50964109e-02,
         1.00187147e-02,  1.24267694e-02, -1.39923632e-01,
         7.68696144e-02,  3.14095356e-02, -4.15251637e-03,
         4.36902493e-02,  1.71250291e-02, -8.00951049e-02,
         5.74006177e-02,  1.89091284e-02,  8.55261385e-02,
         3.96398529e-02, -1.34371802e-01, -1.44369516e-03,
         3.06704547e-03,  1.76854089e-01,  4.44884971e-03,
        -1.69275030e-02,  2.24266127e-02, -4.35050204e-02,
         6.09026849e-03, -9.98166855e-03, -6.23973049e-02,
         1.07372068e-02, -6.04897272e-03, -7.14660585e-02,
        -8.45808443e-03, -3.18019725e-02, -1.00518405e-01,
         2.25882191e-04, -1.89340841e-02, -3.17794010e-02,
         4.00860570e-02,  2.19177771e-02, -2.59528197e-02,
         5.84525131e-02, -8.12509507e-02,  2.12028306e-02,
        -5.02687208e-02,  1.32058123e-02,  1.32680393e-03,
         2.27063559e-02, -3.45793366e-02,  3.91547531e-02,
        -2.09433381e-02,  3.24819540e-03,  4.43960764e-02,
        -9.85357538e-02, -2.88894456e-02, -6.85024587e-03,
         5.38819581e-02,  6.46110624e-02, -2.45059859e-02,
         9.21828821e-02, -7.49869570e-02,  1.23995375e-02,
        -1.00026578e-01, -4.64910492e-02,  6.01570494e-02,
        -2.46480703e-02, -7.08075687e-02, -2.77270097e-02,
         9.72611755e-02,  3.85841131e-02, -1.44293131e-02,
        -7.46873149e-04, -1.04304869e-02, -1.61842760e-02,
         4.43627946e-02,  9.26001836e-03,  7.14165494e-02,
         6.37917444e-02,  4.94930781e-02, -6.02567382e-02,
         4.04805802e-02, -3.42860259e-02, -1.93881001e-02,
         6.61233515e-02,  6.01589195e-02,  1.09370947e-02,
        -5.38626965e-03,  1.44579951e-02,  9.25429687e-02,
        -3.14563662e-02, -1.84350908e-02,  9.91878752e-03,
        -1.85574926e-02,  1.31285691e-03,  2.26819247e-05,
         2.02737516e-03,  2.75256187e-02, -4.81927618e-02,
         5.42825758e-02, -7.32066631e-02,  4.88667563e-02,
         4.98490334e-02, -9.01136268e-03, -4.68905680e-02,
        -4.25887145e-02, -8.19524005e-02,  3.87106352e-02,
         7.85503834e-02,  1.46077052e-32,  1.66706461e-02,
         5.25494367e-02, -1.82450190e-02, -1.26686115e-02,
         6.52837083e-02, -2.11777296e-02, -4.06322926e-02,
         4.14948352e-02, -2.48361547e-02, -1.33067947e-02,
        -5.46752848e-02, -5.99164574e-04, -4.89248801e-03,
        -6.27359748e-02, -3.84878367e-02, -6.13543987e-02,
         8.27405676e-02,  2.34380364e-02, -8.63085501e-03,
         1.31002264e-02,  6.44214824e-02, -4.41361740e-02,
        -6.98633939e-02, -7.36060217e-02, -4.33264114e-02,
         6.96518831e-03, -5.05956523e-02, -1.60911884e-02,
        -5.66793941e-02,  3.35454452e-03,  5.34115434e-02,
         2.47761682e-02, -1.47986384e-02, -2.93242503e-02,
         7.30228424e-02, -1.86833590e-02,  8.13137293e-02,
        -2.69967578e-02, -5.68055622e-02, -6.59388080e-02,
        -5.95397595e-03,  2.85312496e-02, -7.85358176e-02,
        -2.76693422e-03, -3.26474337e-03, -9.28333476e-02,
        -7.27363452e-02, -3.31903584e-02,  1.01411156e-01,
         9.79881808e-02, -9.78740752e-02,  1.98667776e-02,
         2.38836743e-02, -1.81673057e-02, -3.73708159e-02,
         1.96559215e-03,  6.34425730e-02,  1.18270582e-02,
        -1.12041468e-02, -3.87316346e-02,  9.32424366e-02,
         4.26628487e-03, -1.66872721e-02, -6.87464550e-02,
         1.55119151e-02, -4.97754924e-02,  3.34492624e-02,
         8.00032243e-02,  2.12282725e-02,  1.34581864e-01,
        -2.30730064e-02,  5.53858876e-02,  3.07557881e-02,
        -2.93905903e-02,  2.31905505e-02, -9.34306830e-02,
         7.58035481e-02, -5.21203037e-03, -5.14523312e-02,
         3.32689248e-02,  3.67963761e-02, -1.06450971e-02,
         1.01635335e-02, -2.07650457e-02, -5.85519001e-02,
         4.79328968e-02,  2.13694312e-02,  8.76213163e-02,
         3.35489819e-03, -3.80336456e-02, -1.81205124e-02,
         6.87440066e-03,  5.15879542e-02, -4.75599021e-02,
        -6.12065308e-02, -1.45483589e-32,  4.12804866e-03,
         4.59643407e-03, -5.63901775e-02,  4.32479661e-03,
        -1.09442614e-03,  9.31955036e-03, -2.20269021e-02,
         5.79565428e-02, -1.44787543e-02,  4.64156866e-02,
         1.43542841e-01, -6.89756349e-02,  6.09631166e-02,
        -8.93744454e-02,  2.40918528e-02,  2.06009988e-02,
        -2.82415617e-02, -6.48316070e-02,  5.64795323e-02,
        -7.48333847e-03, -3.52058224e-02,  8.51059780e-02,
         1.30359586e-02,  2.02257670e-02, -1.44390445e-02,
        -4.63718474e-02,  1.77209862e-02,  1.59105603e-02,
        -9.51009095e-02, -3.54527757e-02,  2.08696127e-02,
         3.84379528e-03, -8.77918079e-02,  6.44574314e-02,
         1.44170737e-02,  3.84734804e-03,  4.70991395e-02,
         4.94661927e-02,  1.53861940e-02, -2.59578507e-02,
         9.10895243e-02,  1.83307827e-02, -5.89206964e-02,
         2.51991898e-02, -3.30374166e-02,  8.23344737e-02,
         1.74791664e-02,  6.48047328e-02, -1.19673982e-02,
        -3.31778005e-02,  3.00177373e-02,  3.54220495e-02,
        -1.39623741e-02,  6.69272766e-02,  3.87919582e-02,
         6.06916398e-02,  1.17964006e-03, -2.38786787e-02,
        -1.26930431e-01,  1.13847675e-02,  1.59290340e-02,
        -1.29425973e-02, -8.63247812e-02,  8.53659306e-03,
         6.03761226e-02,  1.51121691e-02, -1.19132377e-01,
         1.15234843e-02,  5.97088858e-02, -3.93345393e-02,
         1.55674582e-02,  1.04602240e-02, -4.72457781e-02,
        -2.59243529e-02,  9.98532586e-03,  3.07146609e-02,
        -7.14844018e-02,  6.98966533e-03, -1.55133605e-02,
         2.18864325e-02, -2.78145913e-02,  6.92734122e-02,
        -2.75903996e-02,  2.62429491e-02,  3.52562517e-02,
        -4.26418148e-02,  7.46316509e-04,  6.59866482e-02,
        -5.15105091e-02, -3.58433761e-02, -6.53441809e-03,
        -2.75858752e-02, -1.00125596e-01,  7.83325508e-02,
        -1.45799490e-02, -6.18457250e-08,  2.00325418e-02,
         6.59786463e-02, -2.04702709e-02,  1.64044499e-02,
         7.63001069e-02,  7.32182190e-02,  5.65791316e-03,
        -6.97715557e-04, -3.63795040e-03,  6.02394417e-02,
        -3.27187441e-02, -6.45838007e-02, -5.97952567e-02,
        -1.76695604e-02,  6.10144483e-03, -5.63489227e-03,
        -1.22972235e-01,  6.35818169e-02, -2.19432414e-02,
        -1.16406567e-01,  2.34365407e-02, -7.23525062e-02,
         2.31774021e-02, -6.55987710e-02, -7.42682591e-02,
         2.60146149e-02,  3.59757729e-02,  7.68432990e-02,
        -3.08056623e-02, -2.34793741e-02, -6.30426556e-02,
        -3.62157561e-02, -1.03560146e-02, -4.75603044e-02,
        -2.87522357e-02,  2.96400748e-02, -5.26897470e-03,
         5.67889437e-02, -3.74491094e-03,  3.09612658e-02,
         3.48227881e-02,  3.78607400e-02,  2.10155882e-02,
         2.70691700e-02,  5.25520556e-02,  7.16229305e-02,
        -5.53756580e-03,  4.01093513e-02,  5.16276397e-02,
        -2.67314464e-02,  5.94224669e-02, -4.29223664e-02,
        -1.19761312e-02,  3.05986162e-02, -7.40331635e-02,
         1.84221659e-02, -8.64861999e-03, -8.83558542e-02,
        -5.91983981e-02, -1.00883008e-04,  1.12913609e-01,
         4.57783276e-03, -4.25972342e-02,  3.22622037e-03],
       [ 8.04568827e-03, -3.57392244e-02,  4.93873246e-02,
        -7.19187781e-03,  6.17643353e-04, -9.05685052e-02,
         5.75594865e-02, -4.39445786e-02,  1.74750928e-02,
         5.21202609e-02, -4.62332182e-02,  2.49039344e-02,
         4.80811037e-02,  6.86636269e-02,  3.56147699e-02,
         3.00088935e-02,  2.61450764e-02, -9.05241966e-02,
        -8.02173167e-02,  5.04851155e-02, -7.90870488e-02,
        -1.76851591e-03, -2.48927288e-02,  9.02152807e-02,
         5.83688775e-03, -6.91071376e-02, -6.67965785e-02,
        -6.99117687e-03, -1.04566067e-01, -2.66474262e-02,
         3.05640437e-02,  2.02934202e-02,  2.25454140e-02,
        -4.22681170e-03,  1.11172833e-02,  6.78261220e-02,
         1.06073292e-02,  7.56636113e-02, -8.22778270e-02,
         8.45728349e-03, -6.97611719e-02, -4.21974398e-02,
        -1.05675822e-02,  2.23672967e-02,  5.64496703e-02,
         8.16499535e-03,  1.09344058e-01,  3.16565260e-02,
        -1.76924430e-02, -3.21071297e-02, -3.39975767e-02,
        -4.91855317e-04,  3.72880138e-03,  2.83772312e-02,
        -1.28521305e-02, -1.07931881e-03, -6.32418692e-02,
         6.89900741e-02,  1.77269913e-02, -5.20959347e-02,
         8.28306563e-03,  5.45032024e-02, -5.42099290e-02,
        -4.53332923e-02, -4.07494120e-02, -2.82698553e-02,
         1.23605793e-02, -2.13815905e-02, -2.36265697e-02,
         1.25318225e-02, -2.37170830e-02,  3.97411212e-02,
        -1.24362186e-01,  7.60625973e-02,  5.50833195e-02,
         8.28217119e-02,  2.97119375e-02, -1.84067804e-02,
        -1.96194388e-02,  5.54319583e-02, -3.49143744e-02,
        -4.14677337e-02, -3.37047540e-02,  7.31324628e-02,
         4.41837162e-02,  2.55246032e-02, -8.26404616e-03,
        -1.07323481e-02, -4.26243804e-02, -2.84964102e-03,
         7.38558993e-02,  2.27768105e-02,  7.15358357e-04,
         4.36012261e-02,  5.09079918e-02,  6.38482422e-02,
        -2.73155589e-02, -6.55021369e-02, -7.69265592e-02,
         3.55171412e-02,  9.60494429e-02,  2.18195431e-02,
         1.20155085e-02, -1.17863966e-02, -4.57934849e-03,
        -8.58035870e-03,  3.37149911e-02,  2.31918171e-02,
        -7.58325458e-02, -5.23878783e-02,  4.53933924e-02,
        -3.80786099e-02, -3.34904455e-02,  9.20352340e-02,
         2.87689045e-02, -3.33817229e-02, -1.95855135e-03,
        -3.04527202e-04, -1.70498863e-02,  2.85336170e-02,
        -8.81095976e-02, -4.02252637e-02, -4.00093310e-02,
        -1.03193512e-02, -2.51968522e-02,  2.14093141e-02,
         1.31045327e-01, -5.29633628e-34, -1.09651722e-01,
         1.29811689e-02,  5.92656992e-03,  4.73506525e-02,
        -8.60294141e-03, -3.67089808e-02,  3.05214804e-02,
         5.53066991e-02, -4.71985340e-02, -1.25119016e-02,
        -1.15366451e-01,  9.08002816e-03,  1.07346535e-01,
        -4.94734645e-02, -1.34290690e-02, -4.61562313e-02,
         2.45319884e-02,  9.45083797e-03,  2.04324313e-02,
        -3.99918072e-02, -4.67826203e-02,  2.21171528e-02,
        -4.58187647e-02, -8.13268125e-03, -7.65662920e-03,
         1.92283969e-02,  4.85844240e-02, -2.55902410e-02,
         1.61546015e-03, -1.37180351e-02,  9.67306364e-03,
         7.36415107e-03,  1.14087826e-02,  1.28853470e-01,
         7.71843176e-03,  7.06362575e-02,  2.54451837e-02,
         4.06524539e-02,  2.44039111e-02,  1.43776434e-02,
        -6.00932240e-02,  7.38180727e-02, -2.44701821e-02,
         8.98901448e-02,  3.17051308e-03,  1.01834439e-01,
         4.17741537e-02, -5.95178008e-02, -3.23181301e-02,
         3.80938500e-02,  1.21155735e-02, -4.07835022e-02,
         2.84823570e-02,  4.90988642e-02, -9.35696252e-03,
         6.50074035e-02,  7.23532289e-02, -1.67792812e-02,
        -8.22414737e-03, -1.61573160e-02,  5.96225671e-02,
        -3.36084068e-02,  2.12108139e-02, -6.06090873e-02,
         1.54377669e-01, -7.24146590e-02, -3.77272107e-02,
        -3.26889381e-02, -1.80384505e-03, -1.01960525e-02,
        -1.60677044e-03, -6.91846684e-02,  8.28444511e-02,
         9.88840386e-02,  3.45472968e-03, -9.90247428e-02,
        -3.52826715e-02, -7.13179111e-02, -4.96000610e-02,
        -3.43954563e-02, -8.13042298e-02,  4.81447428e-02,
         5.00677759e-03, -2.21499596e-02, -5.60056902e-02,
         1.00067658e-02, -3.59793641e-02,  1.06184334e-01,
        -4.54196557e-02,  7.16393217e-02, -2.36773379e-02,
         9.98141803e-03,  2.73602251e-02,  1.05985507e-01,
         4.60164025e-02,  9.59027984e-34, -1.12306982e-01,
         2.78912596e-02, -3.35901678e-02,  5.39242215e-02,
        -2.22291742e-02,  1.53769460e-02,  3.10411751e-02,
         3.39010693e-02,  7.43166804e-02,  3.42471190e-02,
        -3.35056381e-03, -2.05350518e-02, -3.62369567e-02,
         2.29334384e-02, -3.01992167e-02, -1.00819930e-01,
         3.29193696e-02,  6.77542612e-02,  1.35644823e-02,
        -5.20552043e-03, -6.58159405e-02,  9.54550654e-02,
        -1.34038674e-02,  1.53884878e-02, -7.22936019e-02,
         9.67835784e-02, -8.08119327e-02, -4.53450857e-03,
        -6.42011166e-02, -4.99278717e-02,  4.64197844e-02,
         2.21340563e-02,  3.13109718e-02,  9.13569406e-02,
        -4.61120307e-02, -1.02761082e-01,  3.04415710e-02,
         5.09876050e-02,  6.70141131e-02,  1.04042552e-02,
         1.63533855e-02,  3.92031148e-02,  2.17154156e-02,
         5.36603890e-02,  3.62809412e-02, -4.22139913e-02,
        -2.47227270e-02,  1.90311782e-02,  3.61723900e-02,
         6.37021512e-02, -3.21581750e-03, -8.50391481e-03,
         3.94655690e-02,  9.02657956e-03,  1.93095449e-02,
         6.60717785e-02,  1.02695301e-02, -4.43853959e-02,
        -1.56523343e-02, -1.55714285e-02,  1.32904137e-02,
        -1.16108870e-02,  4.21831906e-02, -5.44776991e-02,
         1.29237205e-01, -2.25757267e-02,  5.26204035e-02,
        -1.58436671e-02,  9.33164880e-02,  6.38019899e-03,
        -9.36165359e-03, -6.08875267e-02, -3.27307954e-02,
        -3.44816409e-02,  3.29973884e-02, -4.79391776e-02,
        -9.81301218e-02,  2.91165318e-02, -2.70903558e-02,
         1.81866679e-02, -1.73860192e-02, -4.40371595e-02,
        -7.97002614e-02,  3.01646702e-02, -6.35260865e-02,
         1.25963148e-02,  8.50250050e-02, -4.58910801e-02,
         5.81017770e-02, -2.71002855e-02,  8.42775777e-02,
        -4.09972444e-02, -3.37656438e-02,  1.02088647e-02,
        -2.54193135e-02, -1.40610315e-08,  4.94446717e-02,
        -9.04356241e-02, -6.06709793e-02,  8.29529762e-02,
        -3.29032466e-02,  4.14911099e-02,  9.99588892e-03,
         6.96139270e-03,  3.99235217e-03, -3.24333757e-02,
        -3.14657167e-02, -5.33161238e-02, -3.80912647e-02,
         1.62076633e-02,  2.45779362e-02, -7.26419240e-02,
        -6.56893328e-02, -8.23131576e-02, -8.00500810e-02,
        -5.36649339e-02,  5.60895056e-02, -1.10913254e-02,
         9.62131075e-04, -1.22690305e-01, -5.13836704e-02,
         9.96705797e-03,  1.00696497e-02,  1.07073039e-01,
         1.19758090e-02,  1.00423107e-02, -6.28261566e-02,
        -7.49697089e-02, -6.34071417e-03, -2.72200853e-02,
        -1.28096148e-01, -2.62459684e-02, -1.81465074e-02,
        -9.85359997e-02, -3.02989986e-02, -4.02615033e-02,
         9.94290709e-02,  5.35999835e-02,  2.74899211e-02,
        -5.53685380e-03,  8.43570456e-02,  8.35161582e-02,
         3.74304168e-02,  7.11937770e-02,  2.98902858e-02,
         2.32728850e-02, -3.62112671e-02,  6.20540045e-02,
         2.15148237e-02,  5.19733354e-02,  1.45338085e-02,
        -4.60966341e-02,  5.02553806e-02, -7.27027655e-02,
         2.92778909e-02,  5.62662780e-02, -3.86354923e-02,
         1.53832156e-02, -6.23094700e-02, -2.77467091e-02]], dtype=float32)

In [44]:
X = filtered_embeddings
y = df_non_legacy['target_label']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
report = classification_report(y_test, y_pred)
print(report)

                     precision    recall  f1-score   support

     Critical Error       0.97      1.00      0.98        29
              Error       1.00      0.97      0.98        29
        HTTP Status       1.00      1.00      1.00       196
     Resource Usage       1.00      1.00      1.00        29
     Security Alert       1.00      1.00      1.00        81
System Notification       1.00      1.00      1.00        86
        User Action       1.00      1.00      1.00        11

           accuracy                           1.00       461
          macro avg       1.00      1.00      1.00       461
       weighted avg       1.00      1.00      1.00       461

In [45]:
import joblib
joblib.dump(clf, '../models/log_classifier.joblib')

['models/log_classifier.joblib']